

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import xarray as xr



# Loading the nc file once is way faster.
# Assume this will always be run with laporta. (Fix this later if I need to)
laporta = 1
cross_sections = xr.open_dataset('./cross_sections_N2_laporta_subset.nc').load()



def write_reaction_rate_function(df, fn = 'steve_n2v_reaction.py', Ti='Ti', ):
    '''
    This is Python code that writes Python code. 
    It will create a .py file with one function which, given temperatures and relative velocity,
    will return a dictionary where the key is the reaction, and the value is the rate.
    
    df - pandas DataFrame like the one returned by read_reaction_spreadsheet, which has
      "Rate" and "Reaction" columns
    fn - filename for resulting .py file
    Ti - 'Ti' or 'Tf'. Which temperature (ion temperature or effective temperature) to use when
         "Ti" is called for in a reaction rate
      
    '''

    s = """
import numpy as np
import pandas as pd
from numpy import sqrt, exp
import steve_n2v

def rate_coeff(Tn, Ti, Te, v):
    \"""
    This function is auto-generated by some Python code, which reads a xls document, 
    which was copied from my Evernote table (yikes!). It's intended to be faster than looping through 
    the DataFrame each time.

    Rates are given in cm^3 s^-1 or s^-1, or whatever combination of cm, s, ph/nm, etc., makes sense

    Inputs are assumed to be arrays:
        - Tn [K]: neutral temperature
        - Ti [K]: ion temperature (i.e., 2nd central moment of distribution)
        - Te [K]: electron temperature
        - v [m/s]: ion-neutral relative velocity

    Returns a dictionary where keys are reactions and values are rates (array per reaction)
    
    \"""
    
    amu = 1.66e-27 # 1 amu in kg
    k   = 1.38e-23 # Boltzmann constant

    xn = Tn/300
    xi = Ti/300
    xe = Te/300
    
    d = {}

"""
    
    # Atomic masses of all the species we care about
    mass = {
    'O':16,
    'N':14,
    'NO':30,
    'N2':28,
    'O2':32,
    'e':0,
    }
    
    for i in range(len(df)):
        rx = df.iloc[i,0] # reaction string
        rstr = str(df.iloc[i,1]) # rate string
        s += '    # %s\n' % rx
        
        ## Change Ti to Tf if needed
        if Ti=='Tf':
            rstr = rstr.replace('Ti', 'Tf')
            rstr = rstr.replace('xi', 'xf')
            
        ## Compute effective temperature, if needed
        if 'Tf' in rstr:
            ins = rx.split(' → ')[0].split(' + ')
            ins = [x.strip() for x in ins]
            if '+' in ins[0] and '+' not in ins[1]:
                si = ins[0].split('+')[0]#  e.g., O, O2, NO, etc, a key of m
                sn = ins[1].split('(')[0] # e.g., O, O2, NO, etc.
            elif '+' not in ins[0] and '+' in ins[1]:
                si = ins[1].split('+')[0]
                sn = ins[0].split('(')[0]
            else:
                raise Exception('Error in determining which is ion and which is neutral: %s --- %s --- %s' % (rx, ins[0], ins[1]))
            mi = mass[si]
            mn = mass[sn]
            s += '    mi = %i*amu\n'%mi
            s += '    mn = %i*amu\n'%mn
            s += '    Tf = mn/(mi+mn) * (mi*v**2/(3*k) + Ti - Tn) + Tn\n'
            s += '    xf = Tf/300\n'
            
        ## Case 1: it's an if statement
        if rstr[:2]=='if':
#             s += '    r = np.nan\n'
#             s2 = rstr.split('\n')
#             for m in range(len(s2)//2):
#                 cond = s2[2*m][3:-1] # everything to the right of "if " and excluding ":"
#                 rate = s2[2*m+1]
#                 s += '    r%i = %s\n' % (m, rate)
#                 s += '    r[%s] = r%i[%s]\n' % (cond, m, cond)
            s2 = rstr.split('\n')
            for m in range(len(s2)//2):
                s += '    %s\n' % s2[2*m] # if (condition):
                s += '        r =  %s\n' % s2[2*m+1] # condition
            s += '    d["%s"] = r\n\n' % rx

        else: # Case 2: it's a simple expression, but make sure it's the right size
            s += '    d["%s"] =  %s\n\n' % (rx, rstr)

    s += """
    return d
    """

    with open(fn, 'w') as f:
        f.write(s)



def reaction_input_output(df, add_emissions=[]):
    '''
    Unlike previous version, this relies on the user to specify how many v levels by which were included
    in the dataframe.
    
    add_emissions = A list of emission strings to manually add, not included in df. e.g., ['hvN21P','hvcont']
    
    Parse the raw reactions list and return some useful stuff:
    species   - list(str) - all of the species to track
    emissions - list(str) - all of the emissions to track
    din   - dict - a list of reactants for each reaction
    dout  - dict - a list of products for each reaction
    demis - dict - a list of emissions for each reaction
    sidx  - dict - a dict mapping species names to their index 
    '''

    cols = []
    for i in df.index:
        s = df.loc[i, 'Reaction']
        inout = s.split(' → ')
        ins = inout[0].split(' + ')
        outs = inout[1].split(' + ')
        ins = [x.strip() for x in ins]
        outs =  [x.strip() for x in outs]
        cols.extend(ins)
        cols.extend(outs)
    cols = list(dict.fromkeys(cols)) # Just unique entries, preserving order
    # # Remove photons
    species = np.array([s for s in cols if 'hv' not in s])
    emissions = np.array([s for s in cols if 'hv' in s])
    emissions = np.concatenate([emissions, add_emissions])

    # Re-ordering for convenience
    # Take out the NO(v) and reorder them numerically
    species1 = [s for s in species if not s.startswith('NO(v')] # the non-NO(X,v) species
    species0 = [s for s in species if     s.startswith('NO(v')] # NO(v)
    species0 = [f'NO(v={i})' for i in range(len(species0))]
    species = np.concatenate([species0, species1])
    # Take out the N2(v) and reorder them numerically
    species1 = [s for s in species if not s.startswith('N2(v')] # the non-N2(X,v) species
    species0 = [s for s in species if     s.startswith('N2(v')] # N2(v)
    species0 = [f'N2(v={i})' for i in range(len(species0))]
    species = np.concatenate([species0, species1])


    N = len(species)
    Ne = len(emissions)
    M = len(df)
    dfin  = pd.DataFrame(index=df['Reaction'], columns=species, data=np.zeros((M,N),dtype=int) )
    dfout = pd.DataFrame(index=df['Reaction'], columns=species, data=np.zeros((M,N),dtype=int) )
    dfemis= pd.DataFrame(index=df['Reaction'], columns=emissions, data=np.zeros((M,Ne),dtype=int) )
    for i in df.index:
        s = df.loc[i, 'Reaction']
        inout = s.split(' → ')
        ins = inout[0].split(' + ')
        outs = inout[1].split(' + ')
        ins = [x.strip() for x in ins]
        outs =  [x.strip() for x in outs]
        for x in ins:
            dfin.loc[s, x] += 1
        for x in outs:
            if x in species:
                dfout.loc[s, x] += 1
            if x in emissions:
                dfemis.loc[s,x] += 1

    # This code added after I created the above DataFrames, to be converted back to dicts, 
    # because I found that easier. I'm keeping it inelegant like this in case I ever want
    # to use DataFrames again
    # Convert from DataFrame to dict, since that simplifies things.
    # Each (key,value) pair is (reaction, list of relevant reactants or products or emissions)
    din = {}
    dout = {}
    demis = {}
    for rx in dfin.index:
        # This accounts for possibly the same reactant appearing twice (or product)
        din[rx]   = [sp for sp, n in dfin.loc[rx].items()  for _ in range(n) if n > 0]
        dout[rx]  = [sp for sp, n in dfout.loc[rx].items() for _ in range(n) if n > 0]
        demis[rx] = [sp for sp, n in dfemis.loc[rx].items() for _ in range(n) if n > 0]
        
        
    # Convert din, dout, demis to species indices instead of species string keys
    reactions = list(din.keys())
    nin = {}
    nout = {}
    nemis = {}
    for rx in reactions:
        xin = []
        xout = []
        xemis = []
        for s in din[rx]:
            j, = np.where(species==s)
            xin.append(j[0])
        for s in dout[rx]:
            j, = np.where(species==s)
            xout.append(j[0])
        for s in demis[rx]:
            j, = np.where(emissions==s)
            xemis.append(j[0])
        nin[rx] = np.array(xin)
        nout[rx] = np.array(xout)
        nemis[rx] = np.array(xemis)
        
    # Dictionary to convert species name to index
    sidx = {}
    for s in species:
        sidx[s] = np.where(species==s)[0][0]
        
    # Dictionary to convert emission name to index
    eidx = {}
    for e in emissions:
        eidx[e] = np.where(emissions==e)[0][0]
        
    # Be sure to include alternative versions of species names, for flexibility
    if 'N2(v=0)' in species:
        sidx['N2'] = sidx['N2(v=0)']
    if 'NO(v=0)' in species:
        sidx['NO'] = sidx['NO(v=0)']
    if 'O' in species:
        sidx['O(3P)'] = sidx['O']
    if 'N' in species:
        sidx['N(4S)'] = sidx['N']

    # Check for common mistakes
    if 'N2' in species and 'N2(v=0)' in species:
        v = 'N2'
        print(f'\nREACTIONS WITH {v}\n')
        [print(r) for r in din if v in din[r]]
        [print(r) for r in dout if v in dout[r]]
        v = 'N2(v=0)'
        print(f'\nREACTIONS WITH {v}\n')
        [print(r) for r in din if v in din[r]]
        [print(r) for r in dout if v in dout[r]]
        raise Exception("N2 and N2(v=0) shouldn't both be included")
    if 'NO' in species and 'NO(v=0)' in species:
        v = 'NO'
        print(f'\nREACTIONS WITH {v}\n')
        [print(r) for r in din if v in din[r]]
        [print(r) for r in dout if v in dout[r]]
        v = 'NO(v=0)'
        print(f'\nREACTIONS WITH {v}\n')
        [print(r) for r in din if v in din[r]]
        [print(r) for r in dout if v in dout[r]]
        raise Exception("NO and NO(v=0) shouldn't both be included")
    
                
    return species, emissions, din, dout, demis, nin, nout, nemis, sidx, eidx



def eq_dens(s, n, prodrate, drc, nin, nout, species):
    '''
    Compute equilibrium concentration for species s using densities and reaction rates given. Intended
    to be used to compute minor species concentrations.
    
    This was strongly modified from the 2020 version. Production rate is calculated outside module.
    
    s - str - species to compute (e.g., 'NO', 'O+(2D)')
    n - (Ns) array - densities
    prodrate - cm^-3 s^-1. Total production rate at this timestep
    drc - dictionary of reaction rate coefficients, already evaluated as scalars, not formulas
    species - list of str - the list of species names
    '''
    reactions = list(drc.keys())
    Ns = np.shape(n)
    js = np.where(species==s)[0][0]

    lossrate = 0.0 # 1/s
    for jr, rx in enumerate(reactions): # loop over reactions
        # Find product of input species densities and multiply by reaction coefficient
        if js in nout[rx] and js in nin[rx]: # does not affect equilibrium: exclude
            continue
        if js in nin[rx]: # It's a loss rate
            # Note: excluding the species under consideration from the loss rate, since it's 
            # the unknown we're solving for
            lossrate += drc[rx] * np.array([n[jx] for jx in nin[rx] if jx!=js]).prod(axis=0) 
    neq = prodrate/lossrate
    return neq
    


# --- Esposito (2022) vibrational energies ---
# Note that 0-point is defined as dissocation energy, so they are negative
EN2 = np.array([
    -9.7582737, -9.4680532, -9.1819641, -8.8999926, -8.6221262, -8.3483546,
    -8.0786686, -7.8130608, -7.5515254, -7.2940581, -7.0406558, -6.7913172,
    -6.5460423, -6.3048326, -6.0676909, -5.8346214, -5.6056300, -5.3807233,
    -5.1599103, -4.9432004, -4.7306051, -4.5221371, -4.3178106, -4.1176412,
    -3.9216459, -3.7298441, -3.5422552, -3.3589020, -3.1798078, -3.0049980,
    -2.8345000, -2.6683433, -2.5065588, -2.3491802, -2.1962432, -2.0477859,
    -1.9038490, -1.7644762, -1.6297138, -1.4996117, -1.3742228, -1.2536048,
    -1.1378183, -1.0269297, -0.9210100, -0.8201359, -0.7243908, -0.6338653,
    -0.5486585, -0.4688789, -0.3946469, -0.3260958, -0.2633750, -0.2066535,
    -0.1561249, -0.1120140, -0.0745876, -0.0441708, -0.0211762, -0.0061672,
    -0.0000511, 0.0
])

ENO = np.array([
    -6.5096986, -6.2808127, -6.0548686, -5.8319204, -5.6120225, -5.3952293,
    -5.1815960, -4.9711777, -4.7640304, -4.5602103, -4.3597743, -4.1627800,
    -3.9692857, -3.7793507, -3.5930350, -3.4103997, -3.2315073, -3.0564211,
    -2.8852061, -2.7179288, -2.5546572, -2.3954612, -2.2404128, -2.0895861,
    -1.9430575, -1.8009062, -1.6632141, -1.5300666, -1.4015522, -1.2777636,
    -1.1587976, -1.0447560, -0.9357455, -0.8318789, -0.7332760, -0.6400634,
    -0.5523766, -0.4703605, -0.3941711, -0.3239770, -0.2599614, -0.2023247,
    -0.1512878, -0.1070957, -0.0700229, -0.0403806, -0.0185266, -0.0048825, 0.0
])

def k_O_N2v__NOw_N_armenise(v, w, T):
    """
    Rate coefficient for O + N2(v) --> NO(w) + N.
    From Armenise [2023, doi:10.1016/j.chemphys.2023.111937], 
    using the new coefficients in the correction by Armenise [2024, doi:10.1016/j.chemphys.2023.112088]
    
    INPUTS:
     - v = vibrational quantum number for N2
     - w = vibrational quantum number for NO
     - T = temperature in K
    """


    
    
    # Table S4 c0jk coefficients (domain E_NO ≥ E_N2)
    c0_LE = np.array([
     [-23.009142522427709,  7.2103335001933484, -8.7784063954052876,
      -3.1030459351390443,  0.58198334830969678,  9.9785558829684998e-2,
       3.8575685620395486e-4],
     [  3.6251125162862521, 11.916769474703122,   1.6080239358616770,
      -1.6119179512032593,  5.8803059790749547e-2, 0.11814731532636033,
       4.8978001717575083e-4],
     [  1.3494779246584907,  5.1087334804026572,  2.2810438459226763,
       1.6512332771231195e-2, 1.0182985703858796e-2, 6.2214764208374511e-2,
       2.4775823932313270e-4],
     [  0.22146545787575389, 0.83439328866993867, 0.46807170805856418,
       5.6526773345908055e-2, 3.4650912107652156e-3, 1.1716337268134584e-2,
       4.4599364073834758e-5],
     [  1.2914032041086576e-2, 4.5977772388548159e-2, 2.8009146864253043e-2,
       4.5936159105912974e-3, 2.8005852336440121e-4, 6.9575054408147527e-4,
       2.5794895911257976e-6],
     [  0.49248738151172072, 7.2771614885851301,  0.99123307383719061,
        6.2277098569708143,  0.44551242787036921,  1.2654692688132367e-2,
        5.0256102589530263e-5],
     [ -1.9627342205931412e-3, -0.31810618453803224, -6.6520677461372166,
       -8.8744873448291663, -6.0058056465829557,  1.1748272795668318e-4,
        5.8421241221389125e-7]
    ])
    
    # Table S5 c1jk coefficients (domain E_NO ≥ E_N2)
    c1_LE = np.array([
     [-5819.0545441221657, -23075.316162823074,  33744.317289039005,
      10830.301739830727, -6232.1607440092139,  -163.43413689489179,
        -0.62977839797501178],
     [ 4589.8481991415501, -24699.277687250102,   1698.2568368643213,
       6411.7532864056648,  -938.28817851608494,  -220.63845936894731,
        -0.81283252817613838],
     [-3096.6320015542665, -11290.791774441230,  -4564.4830991526414,
        466.94577529725098,  -88.997679463498997,  -100.44136630854963,
        -0.35065075778407084],
     [ -514.50583598501953, -1817.6145429983706, -1017.0253192547095,
        -87.272451586435878,  -10.211373002745816,  -16.904882068134501,
        -5.5391127489453997e-2],
     [  -28.682302771553445,  -96.440711083272248,  -60.248556549179028,
         -8.8528719833948983,  -0.63596404992082012,  -0.91852313535317254,
         -2.8756671925724581e-3],
     [ -774.58050125407783,  2098.7856007559876, 22958.488244190812,
      -17595.977517483603, -15132.354572385459,   -21.109404373240402,
         -8.3699584779262010e-2],
     [   -9.2118455264350274,  262.25468558114324, -1044.7767708131137,
       -17188.031052626862, -7078.4836099072400,    -0.38334564301814755,
         -1.6174367064272354e-3]
    ])
    
    # Table S6 c2jk coefficients (domain E_NO ≥ E_N2)
    c2_LE = np.array([
     [1519759.6944870651, 1156104.3334916057, -8799231.2169090752,
      -378084.36179939611, 591080.65244140476, 42028.610360542829,
       160.63440288449576],
     [2074635.0909713127, 5196281.7613483528, -1378559.9166516699,
      -659547.46775692503,  79575.613066064863, 58961.134462850649,
       213.54026355676572],
     [ 920888.69437954051, 2598691.7012629104,  728527.40490161511,
         561.15853744038020, 9807.5417986310076, 27309.992464035375,
         93.180847086570921],
     [ 156656.75225219197,  444954.11623888399,  201492.04407811663,
        25861.275183643775,  1940.2109048633272,  4728.6021015813976,
         15.320562013265056],
     [   8947.7675053505609,  24850.202924242261,  13087.758436790353,
         2177.5510253525590,   141.99752582407524,   265.69590658563214,
           0.83725386095746612],
     [ 153257.80885007654, -1667447.5473839871, -5264033.1154882153,
       5524224.4237406971, 1385847.3678332167, 4810.9549858303371,
          19.404246080935618],
     [   -113.42340126846867,  -98133.507239691535,  800004.05630615843,
       3931632.0958152148,  79559.039315668546,    57.480173078811148,
           0.27024262570844437]
    ])
    
    
    # Table S1 c0jk coefficients (domain E_NO < E_N2)
    c0_GE = np.array([
     [-21.664540805351141,  1.8055927307833701,  0.42288816108788296,
       6.2410149822479014e-2,  4.2973805094303260e-3,  0.43266910347769605,
      -1.5479364483732591e-2],
     [  8.280292054187026,  12.660816659730742,  5.472823713887802,
       0.9437718303979434,  5.6649342098327796e-2,  0.5225075082375363,
      -0.6964238386092562],
     [-11.51254612514281,   5.014583198730923,   4.03588460940688,
       0.8006576867876057,  5.034330002767643e-2, -19.553069096699556,
      -5.715479003747676],
     [-30.793753079798734, -11.836083381655115, -1.8188096882520812,
      -8.93055549459798e-2,  1.1771300825968428e-3, -25.67691152851578,
      -2.4129932566542034],
     [ -1.80150323835849,  -1.5793092829544935, -0.3915396836883629,
      -4.006082286785953e-2, -1.4470521268909694e-3,  2.9779355101804303,
       4.3832857908353926],
     [ 4.5073321356829787e-2, 3.1320420233968867e-2, 1.2911245811989382e-2,
       1.9236152074286522e-3, 8.998209083479983e-5, 8.610410105530224e-3,
      -1.1919344685134294e-4],
     [ 1.9597405896363843e-4, 1.3175566687702577e-4, 5.294108554185529e-5,
       7.6138184070644086e-6, 3.3655738964952254e-7, 3.9280638106882712e-5,
      -2.7453746844343842e-7]
    ])
    
    # Table S2 c1jk coefficients (domain E_NO < E_N2)
    c1_GE = np.array([
     [-2799.8136284825414, -2963.3704413047922, -1103.049165022408,
       -174.4958690022739, -9.8900002124366004, -329.90686315173463, 19.30733036841305],
     [-6822.159305600929, -9745.404521339276, -3390.8631651669125,
       -476.7393618552051, -24.258389645318218, 4484.067187753205, 786.0395482826239],
     [34177.62682178905, 5033.444372660279, -974.0155705449658,
       -315.11370667797723, -22.158098441700133, 47119.252034450998, 3200.4649053468543],
     [70329.02148520871, 30756.256043165205, 6350.43485629462,
       630.689624702823, 24.111249493613105, 51954.116647921124, -18673.454829208426],
     [-19447.7885225445, -3183.0145728106636, -129.83186271589278,
        19.468870174542243, 1.6399612927906677, -50851.51119382456, -48577.618191208916],
     [ -36.758949065967315, -26.964197070928815, -5.452416759940386,
       -8.501526416428612e-2, 3.645257892306203e-2, -6.366737886389354, 0.20730990581576456],
     [ -0.15764055511730313, -9.869494864789546e-2, -1.1142431643984534e-2,
        2.4774190381814296e-3, 3.6301808895330414e-4, -2.9143960136459347e-2, 6.7988695752254865e-4]
    ])
    
    # Table S3 c2jk coefficients (domain E_NO < E_N2)
    c2_GE = np.array([
     [ 493907.17701092846, 574466.2663749257, 216551.59599778923,
       33383.38227417233, 1817.5122948627163, 26519.049563659075, -6855.816878212284],
     [1227383.0004059384, 2307676.3738783426, 895152.304135034,
       133138.90677392905, 6943.906191391029, -1411953.917901398, -190514.33800458495],
     [-9838231.685777679, -2009284.6414584068, 122136.22091541332,
        71141.78774203811, 5302.053354866069, -11884298.288158197, -555160.48391114],
     [-15162470.077414708, -6849871.238995752, -1410190.4579065272,
       -138080.29770743565, -5208.880452826738, -9797349.342977773, 5129076.145970468],
     [3917784.356967096, 579428.3370295045, 8232.441411495613,
       -5920.873956188403, -413.28503835815854, 10530442.923821872, 9929019.198061129],
     [8245.130014380698, 8171.18936021059, 2540.6685712633107,
        289.8530835409842, 10.23364083581121, 725.7486303002365, -97.20263355655051],
     [36.49328203319021, 33.99830183300178, 9.711585760385205,
        0.9181786049644368, 0.01833481489234273, 3.6365578389927595, -0.3759612950333829]
    ])

    Ev = EN2[v]
    Ew = ENO[w]


    # Select branch coefficients (Tabs S1–S3 vs S4–S6)
    if Ev > Ew:
        c0, c1, c2 = c0_GE, c1_GE, c2_GE  # Tables S1–S3 (Ev > Ew)
    else:
        c0, c1, c2 = c0_LE, c1_LE, c2_LE  # Tables S4–S6 (Ev < Ew)
    
    c = np.array([c0, c1, c2]) # dimensions (i, j, k) = (3, 7, 7)
    
    k = np.arange(5)
    b = (c[:,:,:5] * Ew**k).sum(axis=2) + c[:,:,5]*1/Ew + c[:,:,6]*1/Ew**2
    j = np.arange(5)
    a = (b[:,:5] * Ev**j).sum(axis=1) + b[:,5]*1/Ev + b[:,6]*1/Ev**2
    i = np.arange(3)
    R = np.exp( (a * 1/T**i).sum() )
    return R

    


def k_O_N2v__NO_N_armenise(v, T):
    """
    Sum over all NO(w) product levels of:
    O + N2(v) --> NO(w) + N
    using Armenise (2023, 2024) rates.
    Useful in cases where vib levels of NO are not resolved.
    """
    # w runs only over bound levels (where Ew < 0)
    valid_w = [w for w in range(48) if ENO[w] < 0]
    return sum(k_O_N2v__NOw_N_armenise(v, w, T) for w in valid_w)


def k_O_N2v__NO_N_dmitrieva(v, T):
    """
    Rate coefficient for 
    O + N2(v) --> NO + N
    using Dmitrieva and Zenevich (1984) rates,
    which are used in Pavlov (2011)
    """
    A = np.array([-10.553, -10.761, -10.546, -10.496, -10.413, -10.299, -10.211, -10.099, -9.9925, -9.9557, -9.9303])
    B = np.array([-3.5785, -2.1786, -2.0185, -1.3926, -1.0020, -0.79517, -0.55626, -0.47656, -0.47058, -0.26060, -0.088046])
    C = np.array([0.10993, 0.065508, 0.63923, 0.49675, 0.35965, 0.29601, 0.16353, 0.15306, 0.20699, 0.072218, -0.057985])
    D = np.array([0,       0,        -0.086991, -0.068906, -0.050763, -0.043939, -0.021204, -0.023201, -0.038499, -0.014709, 0.010343])
    
    if v<10:
        return 0.0
        
    elif v<=21:
        i = v-10
        return 10**(A[i] + B[i]*(1000/T) + C[i]*(1000/T)**2 + D[i]*(1000/T)**3)
        
    else: # Assume it's equal to the v=21 rate
        return k_O_N2v__NO_N_dmitrieva(21, T)



def calculate_rate_coefficients(EEDF_eV,EEDF,delta_function=0,electronic_vib_resolution=0,NO_vib=1,laporta=1):
    '''
    Calculates rate coefficients for production of various vibrationally and electronically excited states via electronic impact excitation 
    
    Inputs:
    
        EEDF_eV - array of energies on which the EEDF is defined in eV. NOTE: for a delta_function, this should be a single value
        EEDF - array of EEDF values (units of probability/eV). Should integrate to 1. -> NOTE: NOT THE SAME AS THE EEDF RETURNED BY BOLSIG+, WHICH HAS UNITS OF EV^-3/2
        delta_function - set to 1 if the EEDF is a delta function. In this case, specify EEDF=inf and let EEDF_eV be the energy at which the delta function occurs
        electronic_vib_resolution - some of the N2 triplet states have cross sections that have additional vibrational state resolution. If this flag is set to 0 (default), that is ignored.
        NO_vib - set to 1 if you want to calculate rates for NO vibrational states
        laporta - set to 1 if you want to use the Laporta et al. (2012) N2 vibrational cross sections
    
    Returns:
    
        rate_coefficients - xarray with rate coefficients in cm^3/s
    '''
    if laporta==0:
        raise Exception('Not supported yet')

    #load relevant cross sections (Update: Assume this has already been loaded)
    # if laporta:
    #     cross_sections = xr.open_dataset('./cross_sections_N2_laporta.nc') #CHANGE THIS FILEPATH AS NEEDED!
    # else:
    #     cross_sections = xr.open_dataset('./cross_sections_with_NO_vib.nc') #CHANGE THIS FILEPATH AS NEEDED!
    xsec_eV = cross_sections["eV"]

    #first, do the vibrational states of N2:
    if laporta:
        N2_da = cross_sections["N2_vib_cross_section"]
        vstart = cross_sections["vib_state_start"].values
        vend   = cross_sections["vib_state_end"].values
        k_N2_vib = np.full((vstart.size, vend.size), np.nan, dtype=float)

        # integrate per (vin, vout)
        for i, vin in enumerate(vstart):
            for j, vout in enumerate(vend):
                xsec_cm2 = N2_da.isel(vib_state_start=i, vib_state_end=j).values  # on xsec_eV grid
                if np.all(np.isnan(xsec_cm2)):
                    continue
                k_N2_vib[i, j] = integrate_EEDF(EEDF_eV, EEDF, xsec_eV, xsec_cm2, delta_function=delta_function)

    else: #biagi cross sections
        k_N2_vib = np.empty((len(cross_sections["vib_state"],)))
    
        for vib_state in range(len(cross_sections["vib_state"])):
    
            xsec_cm2 = cross_sections["N2_vib_cross_section"].values[vib_state,:]
            k_N2_vib[vib_state] = integrate_EEDF(EEDF_eV, EEDF, xsec_eV, xsec_cm2, delta_function=delta_function)
        
    #next, vibrational states of NO:
    if NO_vib:
        if laporta: #just changes the coordinates
            NO_da = cross_sections["NO_vib_cross_section"]
            k_NO_vib = np.full((vstart.size, vend.size), np.nan, dtype=float)

            for i, vin in enumerate(vstart):
                for j, vout in enumerate(vend):
                    xsec_cm2 = NO_da.isel(vib_state_start=i, vib_state_end=j).values
                    if np.all(np.isnan(xsec_cm2)):
                        continue
                    k_NO_vib[i, j] = integrate_EEDF(EEDF_eV, EEDF, xsec_eV, xsec_cm2, delta_function=delta_function)

        else:
            k_NO_vib = np.empty((len(cross_sections["vib_state"],)))
            
            for vib_state in range(len(cross_sections["vib_state"])):
    
                xsec_cm2 = cross_sections["NO_vib_cross_section"].values[vib_state,:]
                k_NO_vib[vib_state] = integrate_EEDF(EEDF_eV, EEDF, xsec_eV, xsec_cm2, delta_function=delta_function)
    else:
        k_NO_vib = None

    #repeat for electronic states:
    if electronic_vib_resolution:

        state_name = ['O_1S','O_1D',
                 'N2_A3_0_4','N2_A3_5_9','N2_A3_10_21',
                 'N2_B3_0_3','N2_B3_4_16',
                 'N2_C3_0_4',
                 'N2_Bp3_0_6','N2_Bp3_7_18',
                 'N2_W3_0_5','N2_W3_6_10','N2_W3_11_19']

        k_electronic = np.empty((len(state_name),))

        for el_state in range(len(state_name)):

            xsec_cm2 = cross_sections["electronic_state_cross_section"].values[:,el_state]
            k_electronic[el_state] = integrate_EEDF(EEDF_eV, EEDF, xsec_eV, xsec_cm2, delta_function=delta_function)

    else:

        state_name = ['O_1S','O_1D','N2_A3','N2_B3','N2_C3','N2_Bp3','N2_W3']
        #number of cross sections to combine for each state:
        n_combine = [1,1,3,2,1,2,3]

        k_electronic = np.empty((len(state_name),))

        state_start = 0

        for el_state in range(len(state_name)):

            xsec_cm2 = np.sum(cross_sections["electronic_state_cross_section"].values[:,state_start:state_start+n_combine[el_state]],axis=1)
            k_electronic[el_state] = integrate_EEDF(EEDF_eV, EEDF, xsec_eV, xsec_cm2, delta_function=delta_function)
            state_start = state_start+n_combine[el_state]


    #put it all into an xarray to return
    if laporta:
        # 2D matrices for vib states
        coords = {
            "vib_state_start": cross_sections["vib_state_start"].values,
            "vib_state_end":   cross_sections["vib_state_end"].values,
            "el_state": state_name,
        }
        data_vars = {
            "k_N2_vib": (["vib_state_start", "vib_state_end"], k_N2_vib),
            "k_electronic": (["el_state"], k_electronic),
        }
        if NO_vib:
            data_vars["k_NO_vib"] = (["vib_state_start", "vib_state_end"], k_NO_vib)
    else:
        coords = {
            "vib_state": cs["vib_state"].values,  
            "el_state": state_name,
        }
        data_vars = {
            "k_N2_vib": (["vib_state"], k_N2_vib),
            "k_electronic": (["el_state"], k_electronic),
        }
        if NO_vib:
            data_vars["k_NO_vib"] = (["vib_state"], k_NO_vib)

    rate_coefficients = xr.Dataset(
        data_vars=data_vars,
        coords=coords,
        attrs={"description": "Electron impact excitation rate coefficients for vibrational and electronic states"},
    )

    # adding units to attributes
    if "k_N2_vib" in rate_coefficients:
        rate_coefficients["k_N2_vib"].attrs["units"] = "cm^3/s"
    if NO_vib and "k_NO_vib" in rate_coefficients:
        rate_coefficients["k_NO_vib"].attrs["units"] = "cm^3/s"
    rate_coefficients["k_electronic"].attrs["units"] = "cm^3/s"
    
    return rate_coefficients


def integrate_EEDF(EEDF_eV, EEDF, xsec_eV, xsec_cm2, delta_function=0):
    '''
    Integrates the EEDF over a specified collisional cross section to return the rate coefficient
    
    Inputs:
    
        EEDF_eV - array of energies on which the EEDF is defined in eV. NOTE: for a delta_function, this should be a single value
        EEDF - array of EEDF values (units of probability/eV). Should integrate to 1. -> NOTE: NOT THE SAME AS THE EEDF RETURNED BY BOLSIG+, WHICH HAS UNITS OF EV^-3/2
        xsec_eV - energies on which the cross section is defined
        xsec_cm2 - cross section in cm^2
        delta_function - set to 1 if the EEDF is a delta function. In this case, specify EEDF=inf and let EEDF_eV be the energy at which the delta function occurs
    
    Returns:
    
        k - rate coefficient in cm^3/s
    '''
        
    #important constants
    qe = 1.602e-19 #electron charge (C)
    me = 9.11e-31 #electron mass (kg)
    gamma = np.sqrt(2*qe/me)
        
    #interpolate cross section to EEDF energies
    xsec_interp = np.interp(EEDF_eV,xsec_eV,xsec_cm2)
    #convert to m2:
    xsec_interp = xsec_interp*10**-4
    
    if delta_function:
        k = gamma*xsec_interp*np.sqrt(EEDF_eV)
    else:
        integrand = gamma*EEDF*xsec_interp*np.sqrt(EEDF_eV)
        k = np.trapezoid(integrand[~np.isnan(integrand)],EEDF_eV[~np.isnan(integrand)])
    
    return k*10**6 #converting to cm^3/s

    



import re
def read_BOLSIG(fn = './EEDFs.csv', energy_bins=300):
    '''
    Read the BOLSIG file and return a xarray DataArray with the EEDF.
    
    The EEDF is a probability distribution, in units of eV^-1, integrating to 1. Note that this differs
    from the raw BOLSIG output which is in units of eV^-3/2
    '''
    
    def parse_list_string(s):
        """
        Parses a string like "[val1 val2 val3]" (potentially with newlines and non-breaking spaces)
        into a list of floats.
        Handles potential non-numeric values by returning an empty list.
        """
        if isinstance(s, str):
            # Remove brackets, replace newlines and non-breaking spaces with regular spaces
            # Then strip leading/trailing whitespace
            cleaned_s = re.sub(r'[\[\]\n\xa0]', ' ', s).strip()
            if not cleaned_s: # Handle empty string after cleaning
                return []
            try:
                # Split by any whitespace and convert each part to float
                return [float(x) for x in cleaned_s.split()]
            except ValueError:
                # If any part cannot be converted, return an empty list
                # print(f"Warning: Could not parse some numeric values in string: '{s}'") # Keep this for debugging if needed
                return []
        return [] # Return empty list for non-string inputs

    df = pd.read_csv(fn)
        
    # The zero-E case seems to have some issues so I'll just drop it
    df = df.loc[df['E_Td'] > 0.1]
    
    df['eV_list'] = df['eV'].apply(parse_list_string)
    df['EEDF_list'] = df['EEDF'].apply(parse_list_string)
    
    # Define eV grid
    eVmax = max([max(x) for x in df['eV_list']])
    eVmin = min([min(x) for x in df['eV_list']])
    # eV = np.logspace(np.log10(eVmin),np.log10(eVmax),300)
    eV = np.linspace(np.sqrt(eVmin),np.sqrt(eVmax),energy_bins)**2
        
    block = 498
    n = len(df)
    assert n % block == 0
    
    # containers
    alt_list = []
    Epar_vals = None
    out = []
    
    for start in range(0, n, block):
        dfi = df.iloc[start:start+block]
    
        # altitude sanity check
        assert dfi.altitude.std() == 0
        alt = dfi.altitude.iloc[0]
        alt_list.append(alt)
    
        # grab Epar grid once
        if Epar_vals is None:
            Epar_vals = dfi.E_Td.to_numpy()
    
        # allocate interpolated data (block x len(eV))
        block_arr = np.full((block, len(eV)), np.nan)
    
        # interpolate each Epar slice
        for j, (e_list, f_list) in enumerate(zip(dfi.eV_list, dfi.EEDF_list)):
            block_arr[j] = np.interp(eV, e_list, f_list, left=np.nan, right=np.nan)
    
        out.append(block_arr)
    
    # stack: (n_altitudes, 498, len(eV))
    out = np.stack(out, axis=0)
    
    # reorder dims to (altitude, eV, Epar)
    # current: (alt, Epar, eV)
    out = np.transpose(out, (0, 2, 1))
    
    da = xr.DataArray(
        out,
        dims=("alt", "energy", "Epar"),
        coords={
            "alt": alt_list,
            "energy": eV,
            "Epar": Epar_vals,
        },
        name="EEDF",
    )

    # This is the EEDF in the weird BOLSIG units, eV^-3/2
    da2 = da.bfill(dim="energy").fillna(0) # zero order hold extrap for low energies, zero for high energies    
    # This is in proper probability distribution units 
    eedf = da2 * (da2.energy)**0.5

    eedf.alt.attrs['units'] = 'km'
    eedf.energy.attrs['units'] = 'eV'
    eedf.Epar.attrs['units'] = 'Td'
    eedf.attrs['units'] = 'eV^-1'
    
    return eedf






